### ISSUE TITLE
您好 有關此研究想詢問

### ISSUE THREAD

**Issue by haoolii** [L-M-Sherlock/space_repetition_simulators#1]
由於目前需要追蹤自我學習複習狀態
因此想寫個小工具將複習狀況以及整體章節記憶狀況可視化
但由於才疏學淺似乎無法理解知呼文章解說

現在遇到的問題大概是需要遺忘曲線函數、複習後的遺忘曲線函數。用以顯示出某個項目目前記憶狀態評估
希望可以指點文章大概是哪部分有講解這部分。

**Comment by L-M-Sherlock** [comment]
如果你只是想要用我写的算法，那调用 [ts-fsrs](https://github.com/open-spaced-repetition/ts-fsrs) 即可。

关于间隔重复算法最详细的解释，请看这篇文章：[间隔重复记忆算法：e 天内，从入门到入土。](https://zhuanlan.zhihu.com/p/556020884)

**Comment by haoolii** [comment]
太感謝了！！
